# Generated by Django 3.2.9 on 2022-04-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comemnt',
            new_name='comment',
        ),
    ]
